name: 'CI'
on:
  pull_request:

env:
  IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}

jobs:
  tests:
    name: Run tests
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      branch_ref: ${{ github.ref }}