name: Update Changelog

on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  update_changelog:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only run when the PR was merged. The 'closed' state also includes closed but not merged PRs
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # We want to update our changelog on main
          ref: 'main'

      - name: Install utilities
        run: sudo apt-get install jq

      - name: Get PR information
        id: pr
        uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d # v2.4.0
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        run: |
          PR_DATA='${{ steps.pr.outputs.data }}'
          PR_LINE=$(echo $PR_DATA | jq -r '"- \(.title) ([#\(.number)](\(.html_url))) - [@\(.user.login)](\(.user.html_url)) - \(.merged_at | if . == null then "" else . | fromdateiso8601 | strftime("%Y-%m-%d") end)"')
          sed -i "/## Unreleased/ a $PR_LINE" CHANGELOG.md
          git add CHANGELOG.md

      - name: Commit changes
        uses: grafana/github-api-commit-action@ccf9b520c5698380ad3b9619c5add427369b7ef1 # v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update changelog [BOT]'
